openapi: 3.0.0
info:
  title: ReShare Index
  version: v1
paths:
  /reshare-index/shared-titles:
    parameters:
      - $ref: headers/okapi-tenant.yaml
      - $ref: headers/okapi-token.yaml
      - $ref: headers/okapi-url.yaml
      - $ref: parameters/facets.yaml
      - $ref: parameters/limit.yaml
      - $ref: parameters/query.yaml
      - $ref: parameters/offset.yaml
    get:
      description: Get shared titles
      operationId: getSharedTitles
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: schemas/sharedTitles.json
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
    put:
      description: Enter a title for sharing
      operationId: putSharedTitle
      reponse:
        "201":
          "description": OK
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: {"error":"Invalid JSON in request"}
    trait_404:
      description: Not Found
      content:
        text/plain:
          schema:
            type: string
            example: Identifier 596d9f60-cda3-44d2-a4a1-2f48b7d4d23c not found
        application/json:
          schema:
            type: object
            example: {"error":"Identifier 596d9f60-cda3-44d2-a4a1-2f48b7d4d23c not found"}
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
  schemas:
    errors:
      $ref: schemas/errors.json

